version: "3.7"
services:
  micro_01:
    build:
      args:
        user: thiago
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./web:/var/www
    networks:
      - microservices

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./web:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - microservices

  db_micro_01:
    image: mysql:5.7.22
    restart: unless-stopped
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: micro_01
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql/
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
